# -*- coding: utf-8 -*-
"""mlu게임.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcIUNxHbND8vXztX69b9R7kU7Y5m3FpY
"""

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>MLU-w 분석기 게임</title>
  <style>
    body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
    input, button { padding: 10px; margin: 5px; }
    #result { margin-top: 20px; font-size: 18px; font-weight: bold; }
  </style>
</head>
<body>
  <h1>MLU-w 분석기 게임</h1>
  <p>문장을 입력하면 MLU-w(평균 발화 길이)를 계산합니다.</p>

  <input type="text" id="sentence" placeholder="문장을 입력하세요">
  <button onclick="analyze()">분석하기</button>

  <div id="result"></div>

  <script>
    function analyze() {
      const sentence = document.getElementById("sentence").value.trim();
      if (!sentence) {
        document.getElementById("result").innerText = "문장을 입력하세요!";
        return;
      }

      // 단어 단위로 분리
      const words = sentence.split(/\s+/);
      const wordCount = words.length;

      // MLU-w 계산 (여기서는 단순히 단어 수 평균으로 가정)
      const mluw = wordCount;

      document.getElementById("result").innerText =
        `입력된 문장: "${sentence}"\n단어 수: ${wordCount}\nMLU-w: ${mluw}`;
    }
  </script>
</body>
</html>

"""```markdown
이전 셀의 HTML, CSS, JavaScript 코드를 Colab에서 렌더링하려면 Python 셀에서 `IPython.display.HTML`을 사용해야 합니다. 아래 코드를 실행하면 웹 페이지가 Colab 출력 영역에 표시됩니다.
```
"""

from IPython.display import HTML

html_content = """
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>MLU-w 분석기 게임</title>
  <style>
    body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
    input, button { padding: 10px; margin: 5px; }
    #question { margin-top: 20px; font-size: 20px; font-weight: bold; color: #333; }
    #feedback { margin-top: 10px; font-size: 18px; font-weight: bold; }
    #correctAnswer { margin-top: 5px; font-size: 16px; color: #555; }
    #result { margin-top: 20px; font-size: 18px; font-weight: bold; }
    .correct { color: green; }
    .incorrect { color: red; }
  </style>
</head>
<body>
  <h1>MLU-w 분석기 게임</h1>
  <p>제시된 문장의 MLU-w(평균 발화 길이)를 계산하여 입력하세요.</p>

  <div id="question"></div>
  <input type="text" id="userMluw" placeholder="MLU-w를 입력하세요">
  <button onclick="checkAnswer()">정답 확인</button>

  <div id="feedback"></div>
  <div id="correctAnswer"></div>

  <div id="result"></div>

  <div>
    <button onclick="nextProblem()" id="nextButton" style="display: none;">다음으로</button>
    <button onclick="resetGame()">처음으로</button>
  </div>

  <script>
    const questions = [
      { sentence: "엄마 저 피자랑 고구마랑 감자 주세요.", mluw: 6 },
      { sentence: "나는 오늘 어린이집에서 친구랑 같이 그림 그렸어.", mluw: 7 },
      { sentence: "아빠랑 공원에 가서 시소 타고 미끄럼틀도 탔어요.", mluw: 7 },
      { sentence: "맛있는 초콜릿 케이크 먹고 싶어요. 생일 선물로 주세요.", mluw: 9 },
      { sentence: "하늘에 반짝이는 별이 정말 예뻐요.", mluw: 6 },
      { sentence: "동생이 내 장난감 가지고 놀아서 조금 화가 났어요.", mluw: 8 }
    ];
    let currentQuestionIndex = 0;

    function calculateMluw(sentence) {
      if (!sentence) return 0;
      const words = sentence.split(/\s+/).filter(word => word.length > 0); // 공백을 여러 개 넣어도 단어 수 정확히 계산
      return words.length;
    }

    function loadQuestion() {
      if (currentQuestionIndex >= questions.length) {
        document.getElementById("question").innerText = "모든 문제를 다 풀었습니다! 처음으로 버튼을 눌러 다시 시작하세요.";
        document.getElementById("userMluw").style.display = 'none';
        document.querySelector('button[onclick="checkAnswer()"]').style.display = 'none';
        document.getElementById("feedback").innerText = '';
        document.getElementById("correctAnswer").innerText = '';
        document.getElementById("result").innerText = '';
        document.getElementById("nextButton").style.display = 'none';
        return;
      }

      const questionData = questions[currentQuestionIndex];
      document.getElementById("question").innerText = `문제: "${questionData.sentence}"`;
      document.getElementById("userMluw").value = '';
      document.getElementById("userMluw").style.display = 'inline-block';
      document.querySelector('button[onclick="checkAnswer()"]').style.display = 'inline-block';
      document.getElementById("feedback").innerText = '';
      document.getElementById("correctAnswer").innerText = '';
      document.getElementById("result").innerText = '';
      document.getElementById("nextButton").style.display = 'none'; // 다음 버튼 숨기기
    }

    function checkAnswer() {
      const userInput = document.getElementById("userMluw").value.trim();
      const questionData = questions[currentQuestionIndex];

      if (!userInput) {
        document.getElementById("feedback").className = 'incorrect';
        document.getElementById("feedback").innerText = "MLU-w 값을 입력해주세요!";
        document.getElementById("correctAnswer").innerText = '';
        return;
      }

      const userMluw = parseInt(userInput);
      const actualMluw = questionData.mluw;

      const sentenceFromQuestion = questionData.sentence;
      const wordCountFromQuestion = calculateMluw(sentenceFromQuestion);

      document.getElementById("result").innerText =
        `제시 문장: "${sentenceFromQuestion}"\n단어 수: ${wordCountFromQuestion}`;

      if (userMluw === actualMluw) {
        document.getElementById("feedback").className = 'correct';
        document.getElementById("feedback").innerText = "정답입니다!";
        document.getElementById("correctAnswer").innerText = '';
      } else {
        document.getElementById("feedback").className = 'incorrect';
        document.getElementById("feedback").innerText = "오답입니다.";
        document.getElementById("correctAnswer").innerText = `정답 MLU-w: ${actualMluw}`; // 정답 표시
      }
      document.getElementById("nextButton").style.display = 'inline-block'; // 다음 버튼 표시
      document.getElementById("userMluw").style.display = 'none'; // 입력창 숨기기
      document.querySelector('button[onclick="checkAnswer()"]').style.display = 'none'; // 정답 확인 버튼 숨기기
    }

    function nextProblem() {
      currentQuestionIndex++;
      loadQuestion();
    }

    function resetGame() {
      currentQuestionIndex = 0;
      document.getElementById("userMluw").style.display = 'inline-block';
      document.querySelector('button[onclick="checkAnswer()"]').style.display = 'inline-block';
      loadQuestion();
    }

    // 초기 로드 시 첫 번째 문제 표시
    window.onload = loadQuestion;
  </script>
</body>
</html>
"""

display(HTML(html_content))

import pandas as pd
from kiwipiepy import Kiwi
from ipywidgets import widgets, Layout
from IPython.display import display, clear_output, HTML

kiwi = Kiwi()

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수 (메인 분석기에서 추출)
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]
    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = [] # 각 발화의 어절 수를 저장할 리스트

    for i, utt in enumerate(utterances):
        word_count = len(utt.split()) # 공백을 기준으로 어절 수 계산
        utterance_word_counts.append(word_count)
        utterance_details.append(f" - 발화 {i+1}: '{utt}' (어절수: {word_count})")

    if utterance_word_counts:
        total_utterances = len(utterances)
        average_word_count = sum(utterance_word_counts) / total_utterances
        mlu_w = round(average_word_count, 2)
        return {
            "utterance_details": utterance_details,
            "total_utterances": total_utterances,
            "mlu_w": mlu_w
        }, utterances
    else:
        return None, None

# ──────────────────────────────────────────────────────
# MLU-w 전용 UI 위젯
# ──────────────────────────────────────────────────────
mluw_text_input = widgets.Textarea(
    placeholder="MLU-w를 분석할 발화를 입력하세요 (엔터로 구분)...",
    layout=Layout(width="98%", height="120px"),
    value="안녕하세요. 저는 오늘 학교에 갑니다. 재미있게 공부할 거예요."
)
mluw_analyze_btn = widgets.Button(
    description="🗣️ MLU-w 분석",
    button_style="primary",
    layout=Layout(width="auto", margin="10px 0 20px 0")
)
mluw_output_view = widgets.Output()

# ──────────────────────────────────────────────────────
# MLU-w 이벤트 핸들러
# ──────────────────────────────────────────────────────
def on_mluw_analyze_click(b):
    with mluw_output_view:
        clear_output(wait=True)
        text_content = mluw_text_input.value
        if not text_content.strip():
            display(HTML("<p style='color:red;'>분석할 텍스트를 입력해주세요.</p>"))
            return

        results, _ = run_mluw_analysis(text_content)

        if results:
            display(HTML(f"<div style='margin-top:10px;padding:10px;background:#e0f2f7;border-left:5px solid #2196f3;font-weight:bold;'>입력 텍스트:</div>"))
            print(text_content)
            display(HTML(f"<div style='margin-top:20px;padding:10px;background:#e0f2f7;border-left:5px solid #2196f3;font-weight:bold;'>각 발화의 어절 수:</div>"))
            for detail in results["utterance_details"]:
                print(detail)
            display(HTML(f"<div style='margin-top:20px;padding:10px;background:#e0f2f7;border-left:5px solid #2196f3;font-weight:bold;'>총 발화 수: {results['total_utterances']}</div>"))
            display(HTML(f"<div style='margin-top:10px;padding:10px;background:#e0f2f7;border-left:5px solid #2196f3;font-weight:bold;font-size:1.2em;'>MLU-w (평균 발화 길이 - 어절 기준): <span style='color:#059669;'>{results['mlu_w']}</span></div>"))
        else:
            display(HTML("<p style='color:orange;'>분석할 발화가 없습니다.</p>"))

mluw_analyze_btn.on_click(on_mluw_analyze_click)

# ──────────────────────────────────────────────────────
# MLU-w UI 표시
# ──────────────────────────────────────────────────────
display(HTML("<h2>🗣️ MLU-w (어절 기반 평균 발화 길이) 분석</h2>"))
display(mluw_text_input, mluw_analyze_btn, mluw_output_view)

"""```markdown
이전에 만들었던 MLU-w 게임은 HTML/JavaScript로 웹 브라우저에서 직접 실행되는 형태였기 때문에, Python의 `kiwipiepy` 라이브러리를 사용하여 더 정확한 MLU-w 분석 기능을 통합하기 어려웠습니다.

사용자님의 요청에 따라, `kiwipiepy`를 활용한 정교한 MLU-w 분석 기능을 게임에 적용하기 위해 Python의 `ipywidgets`를 사용하여 게임을 재구현합니다. 이 방식은 Colab 환경에서 Python 백엔드와 상호작용하며 게임을 실행할 수 있도록 합니다.

**게임 방법:**
1. 제시된 문장을 읽고 MLU-w(어절 기준)를 계산합니다.
2. "MLU-w 입력" 필드에 계산한 값을 입력하고 "정답 확인" 버튼을 누릅니다.
3. 정답 여부와 실제 MLU-w 값이 표시됩니다.
4. "다음으로" 버튼을 눌러 다음 문제로 이동하거나, "처음으로" 버튼을 눌러 게임을 다시 시작합니다.
```
"""

ㅁ

from ipywidgets import widgets, Layout
from IPython.display import display, clear_output, HTML

!pip install kiwipiepy > /dev/null 2>&1 # kiwipiepy 라이브러리 설치
from kiwipiepy import Kiwi # Kiwi import 추가

kiwi = Kiwi() # Kiwi 객체 초기화 추가

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]
    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = [] # 각 발화의 어절 수를 저장할 리스트

    for i, utt in enumerate(utterances):
        # Use kiwi.extract_words() for a more intuitive '어절' count based on the user's definition
        words = kiwi.extract_words(utt)
        word_count = len(words)

        utterance_word_counts.append(word_count)
        utterance_details.append(f" - 발화 {i+1}: '{utt}' (어절수: {word_count})")

    if utterance_word_counts:
        total_utterances = len(utterances)
        average_word_count = sum(utterance_word_counts) / total_utterances
        mlu_w = round(average_word_count, 2)
        return {
            "utterance_details": utterance_details,
            "total_utterances": total_utterances,
            "mlu_w": mlu_w
        }, utterances
    else:
        return None, None

# ──────────────────────────────────────────────────────
# MLU-w 게임용 질문 데이터 (kiwipiepy 분석 결과에 맞춰 업데이트)
# ──────────────────────────────────────────────────────
# Recalculating mluw values using the updated run_mluw_analysis logic (using kiwi.extract_words())
questions = [
    { "sentence": "엄마 저 피자랑 고구마 주세요. 맛있게 구워 주세요.", "mluw": 4.5 },
    { "sentence": "형아 나 밥. 나 배고파.", "mluw": 2.5 },
    { "sentence": "아빠랑 공원에 갔어요. 시소 타고 미끄럼틀도 탔어요.", "mluw": 5 },
    { "sentence": "맛있는 케이크 먹고 싶어요. 선물로 주세요.", "mluw": 3.5 },
    { "sentence": "엄마 하늘 봐요. 하늘에 반짝해요. 별이 정말 예뻐요.", "mluw": 3.33 },
    { "sentence": "동생이 내 장난감 가지고 놀아요. 저 화가 났어요.", "mluw": 5.0 }
]

current_question_index = 0

# ──────────────────────────────────────────────────────
# UI 위젯 정의
# ──────────────────────────────────────────────────────
game_output = widgets.Output()
question_label = widgets.HTML("<h2>♡MLU-w 게임 시작♡</h2>")
user_input = widgets.Text(
    placeholder="MLU-w를 입력하세용",
    description="MLU-w:",
    layout=Layout(width="auto")
)
check_button = widgets.Button(
    description="정답 확인",
    button_style="info",
    layout=Layout(width="auto", margin="5px")
)
next_button = widgets.Button(
    description="다음으로",
    button_style="success",
    layout=Layout(width="auto", margin="5px", display="none") # 초기에는 숨김
)
reset_button = widgets.Button(
    description="처음으로",
    button_style="danger",
    layout=Layout(width="auto", margin="5px")
)
feedback_label = widgets.HTML("")
result_label = widgets.HTML("")

# ──────────────────────────────────────────────────────
# 게임 로직 함수
# ──────────────────────────────────────────────────────
def load_question():
    global current_question_index
    with game_output:
        clear_output(wait=True)
        feedback_label.value = ""
        result_label.value = ""
        user_input.value = ""
        user_input.layout.display = "flex"
        check_button.layout.display = "flex"
        next_button.layout.display = "none"

        if current_question_index >= len(questions):
            question_label.value = "<h2>모든 문제를 다 풀었습니다!</h2><p>아래 '처음으로' 버튼을 눌러 다시 시작하세요.</p>"
            user_input.layout.display = "none"
            check_button.layout.display = "none"
            next_button.layout.display = "none"
        else:
            q_data = questions[current_question_index]
            question_label.value = f"<h2>문제: \"{q_data['sentence']}\"</h2>"
            display(question_label, user_input, check_button, next_button, reset_button, feedback_label, result_label)

def check_answer(b):
    global current_question_index
    with game_output:
        clear_output(wait=True)
        q_data = questions[current_question_index]
        user_answer = user_input.value.strip()

        if not user_answer:
            feedback_label.value = "<p style='color:red; font-weight:bold;'>MLU-w 값을 입력해주세요!</p>"
            result_label.value = ""
            display(question_label, user_input, check_button, next_button, reset_button, feedback_label, result_label)
            return

        try:
            user_mluw = float(user_answer)
        except ValueError:
            feedback_label.value = "<p style='color:red; font-weight:bold;'>유효한 숫자를 입력해주세요!</p>"
            result_label.value = ""
            display(question_label, user_input, check_button, next_button, reset_button, feedback_label, result_label)
            return

        # Keep run_mluw_analysis for internal debugging/logging, but its output will no longer be displayed to the user.
        analysis_results, _ = run_mluw_analysis(q_data['sentence'])
        # actual_mluw_calculated = analysis_results['mlu_w'] if analysis_results else 0 # No longer used for display

        correct_mluw_from_data = q_data['mluw']

        # Start building result_label.value with the sentence
        result_label.value = f"<p>제시 문장: \"{q_data['sentence']}\"</p>"

        if user_mluw == correct_mluw_from_data:
            feedback_label.value = "<p style='color:green; font-weight:bold;'>정답입니다!</p>"
            # Always show the correct MLU-w from the data, as requested, replacing '분석된 어절 수'
            result_label.value += f"<p style='color:#555;'>정답 MLU-w: {correct_mluw_from_data}</p>"
        else:
            feedback_label.value = f"<p style='color:red; font-weight:bold;'>오답입니다.</p>"
            # For an incorrect answer, only show the correct MLU-w from the data
            result_label.value += f"<p style='color:#555;'>정답 MLU-w: {correct_mluw_from_data}</p>"

        user_input.layout.display = "none"
        check_button.layout.display = "none"
        next_button.layout.display = "flex" # 다음 버튼 표시
        display(question_label, user_input, check_button, next_button, reset_button, feedback_label, result_label)

def next_problem(b):
    global current_question_index
    current_question_index += 1
    load_question()

def reset_game(b):
    global current_question_index
    current_question_index = 0
    load_question()

# ──────────────────────────────────────────────────────
# 이벤트 핸들러 연결
# ──────────────────────────────────────────────────────
check_button.on_click(check_answer)
next_button.on_click(next_problem)
reset_button.on_click(reset_game)

# ──────────────────────────────────────────────────────
# 게임 UI 표시 및 초기 로드
# ──────────────────────────────────────────────────────
display(HTML("<h1>MLU-w를 맞혀라!♡ (kiwipiepy 기반)</h1>"))
display(game_output)
load_question()

import subprocess
import sys

def install_package(package):
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        print(f"Successfully installed {package}")
    except subprocess.CalledProcessError as e:
        print(f"Error installing {package}: {e}")

install_package("streamlit")
install_package("kiwipiepy")

"""이제 아래 코드를 `mluw_game.py`라는 이름의 파일로 저장하세요. 그 다음, 터미널(Colab에서는 '터미널 열기' 메뉴를 통해 접근)을 열고, 해당 파일이 있는 디렉토리로 이동한 후 다음 명령어를 실행하면 됩니다.

```bash
streamlit run mluw_game.py
```

Colab 환경에서는 Streamlit 앱을 직접 브라우저로 띄우는 것이 아니라, 보통 `ngrok` 같은 서비스를 통해 외부에서 접근할 수 있도록 포트 포워딩을 설정해야 합니다. 하지만 로컬 환경이나 적절한 서버 환경에서는 위 명령어만으로 웹 앱이 실행됩니다.
"""

import streamlit as st
from kiwipiepy import Kiwi

# Streamlit 앱의 제목 설정
st.set_page_config(page_title="MLU-w를 맞혀라! (kiwipiepy 기반)", layout="centered")

st.title("MLU-w를 맞혀라!♡ (kiwipiepy 기반)")
st.markdown("제시된 문장의 MLU-w(어절 기준)를 계산하여 입력하세요.")

# Kiwi 객체를 캐시하여 앱이 다시 실행될 때마다 초기화되지 않도록 합니다.
@st.cache_resource
def get_kiwi():
    return Kiwi()

kiwi = get_kiwi()

# ──────────────────────────────────────────────────────
# MLU-w 분석 함수
# ──────────────────────────────────────────────────────
def run_mluw_analysis(text_content):
    sents = kiwi.split_into_sents(text_content)
    utterances = [s.text.strip() for s in sents if s.text.strip()]
    if not utterances:
        return None, None

    utterance_details = []
    utterance_word_counts = []

    for i, utt in enumerate(utterances):
        words = kiwi.extract_words(utt)
        word_count = len(words)
        utterance_word_counts.append(word_count)
        utterance_details.append(f" - 발화 {i+1}: '{utt}' (어절수: {word_count})")

    if utterance_word_counts:
        total_utterances = len(utterances)
        average_word_count = sum(utterance_word_counts) / total_utterances
        mlu_w = round(average_word_count, 2)
        return {
            "utterance_details": utterance_details,
            "total_utterances": total_utterances,
            "mlu_w": mlu_w
        }, utterances
    else:
        return None, None

# ──────────────────────────────────────────────────────
# MLU-w 게임용 질문 데이터
# ──────────────────────────────────────────────────────
questions = [
    { "sentence": "엄마 저 피자랑 고구마 주세요. 맛있게 구워 주세요.", "mluw": 4.5 },
    { "sentence": "형아 나 밥. 나 배고파.", "mluw": 2.5 },
    { "sentence": "아빠랑 공원에 갔어요. 시소 타고 미끄럼틀도 탔어요.", "mluw": 5.0 },
    { "sentence": "맛있는 케이크 먹고 싶어요. 선물로 주세요.", "mluw": 3.5 },
    { "sentence": "엄마 하늘 봐요. 하늘에 반짝해요. 별이 정말 예뻐요.", "mluw": 3.33 },
    { "sentence": "동생이 내 장난감 가지고 놀아요. 저 화가 났어요.", "mluw": 5.0 }
]

# ──────────────────────────────────────────────────────
# Streamlit 세션 상태 초기화
# ──────────────────────────────────────────────────────
if 'current_question_index' not in st.session_state:
    st.session_state.current_question_index = 0
if 'feedback_message' not in st.session_state:
    st.session_state.feedback_message = ""
if 'result_message' not in st.session_state:
    st.session_state.result_message = ""
if 'show_input' not in st.session_state:
    st.session_state.show_input = True
if 'show_next_button' not in st.session_state:
    st.session_state.show_next_button = False

# ──────────────────────────────────────────────────────
# 게임 로직 함수
# ──────────────────────────────────────────────────────
def load_question():
    st.session_state.feedback_message = ""
    st.session_state.result_message = ""
    st.session_state.user_input_value = ""
    st.session_state.show_input = True
    st.session_state.show_next_button = False

def check_answer_callback():
    q_data = questions[st.session_state.current_question_index]
    user_answer = st.session_state.user_mluw_input

    if not user_answer:
        st.session_state.feedback_message = "<p style='color:red; font-weight:bold;'>MLU-w 값을 입력해주세요!</p>"
        st.session_state.result_message = ""
        st.session_state.show_input = True
        st.session_state.show_next_button = False
        return

    try:
        user_mluw = float(user_answer)
    except ValueError:
        st.session_state.feedback_message = "<p style='color:red; font-weight:bold;'>유효한 숫자를 입력해주세요!</p>"
        st.session_state.result_message = ""
        st.session_state.show_input = True
        st.session_state.show_next_button = False
        return

    correct_mluw_from_data = q_data['mluw']

    st.session_state.result_message = f"<p>제시 문장: \"{q_data['sentence']}\"</p>"

    if abs(user_mluw - correct_mluw_from_data) < 0.01: # 부동 소수점 비교
        st.session_state.feedback_message = "<p style='color:green; font-weight:bold;'>정답입니다!</p>"
    else:
        st.session_state.feedback_message = "<p style='color:red; font-weight:bold;'>오답입니다.</p>"
    st.session_state.result_message += f"<p style='color:#555;'>정답 MLU-w: {correct_mluw_from_data}</p>"

    st.session_state.show_input = False
    st.session_state.show_next_button = True

def next_problem_callback():
    st.session_state.current_question_index += 1
    load_question()

def reset_game_callback():
    st.session_state.current_question_index = 0
    load_question()

# ──────────────────────────────────────────────────────
# Streamlit UI 렌더링
# ──────────────────────────────────────────────────────
if st.session_state.current_question_index >= len(questions):
    st.header("모든 문제를 다 풀었습니다!")
    st.write("아래 '처음으로' 버튼을 눌러 다시 시작하세요.")
    st.session_state.show_input = False
    st.session_state.show_next_button = False
else:
    q_data = questions[st.session_state.current_question_index]
    st.subheader(f"문제: \"{q_data['sentence']}\"")

    if st.session_state.show_input:
        st.text_input("MLU-w를 입력하세용", key="user_mluw_input", on_change=None)
        st.button("정답 확인", on_click=check_answer_callback)

    st.markdown(st.session_state.feedback_message, unsafe_allow_html=True)
    st.markdown(st.session_state.result_message, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        if st.session_state.show_next_button:
            st.button("다음으로", on_click=next_problem_callback)
    with col2:
        st.button("처음으로", on_click=reset_game_callback)

# 앱이 처음 로드될 때 또는 리셋 시 질문을 로드합니다.
if st.session_state.get('initial_load', True):
    load_question()
    st.session_state.initial_load = False